---
# This playbook installs Rackspace Private Cloud v10.1

- name: Install Rackspace Private Cloud v10.1
  hosts: all
  tasks:
    - name: Ping Nodes
      ping:

    - name: Install Packages
      apt: name={{ item }} state=present
      with_items:
        - colordiff
        - fping

    - name: Add Nodes Hosts File Entries
      lineinfile: dest=/etc/hosts regexp='^{{ hostvars[item].ansible_eth2.ipv4.address }} {{ hostvars[item].node_name }}' line='{{ hostvars[item].ansible_eth2.ipv4.address }} {{ hostvars[item].node_name }}' insertafter=EOF state=present
      with_items: groups['all']

    - name: Set Environment Variables and Force Color Prompt
      lineinfile: dest=/root/.bashrc regexp='{{ item.regexp }}' line='{{ item.line }}' insertafter=EOF state=present
      with_items:
        - { regexp: '^(#)?force_color_prompt',      line: 'force_color_prompt=yes' }
        - { regexp: '^export MY_HEAT_STACK_PREFIX', line: 'export MY_HEAT_STACK_PREFIX={{ heat_stack_prefix }}' }
        - { regexp: '^export MY_NODE_ID',           line: 'export MY_NODE_ID={{ node_id }}' }
        - { regexp: '^export MY_IP',                line: 'export MY_IP={{ hostvars[inventory_hostname].ansible_eth2.ipv4.address }}' }
        - { regexp: '^export MY_PRIVATE_IP',        line: 'export MY_PRIVATE_IP={{ hostvars[inventory_hostname].ansible_eth2.ipv4.address }}' }
        - { regexp: '^export MY_PUBLIC_IP',         line: 'export MY_PUBLIC_IP={{ hostvars[inventory_hostname].ansible_eth0.ipv4.address }}' }

    - name: Check Connectivity
      command: fping infra1 infra2 infra3 logger1 compute1 compute2 block1 object1
      changed_when: False

    - name: Partition Disk (Primary / Extended)
      shell: |
        fdisk {{ item.device }} <<EOF
        n
        {{ item.partition_type }}
        {{ item.partition_number }}
        {{ item.partition_start }}
        {{ item.partition_stop }}
        w
        EOF
        partprobe {{ item.device }} creates={{ item.device }}{{ item.partition_number }}
      when: node_name in item.node_names
      with_items:
        - node_names: [ infra1, infra2, infra3 ]
          device: /dev/xvda
          partition_type: p
          partition_number: 2
          partition_start: ''
          partition_stop: +110G
        - node_names: [ logger1 ]
          device: /dev/xvda
          partition_type: p
          partition_number: 2
          partition_start: ''
          partition_stop: +25G
        - node_names: [ compute1, compute2, object1 ]
          device: /dev/xvda
          partition_type: p
          partition_number: 2
          partition_start: ''
          partition_stop: +10G
        - node_names: [ block1 ]
          device: /dev/xvda
          partition_type: p
          partition_number: 2
          partition_start: ''
          partition_stop: +15G
        - node_names: [ block1 ]
          device: /dev/xvda
          partition_type: p
          partition_number: 3
          partition_start: ''
          partition_stop: +50G
        - node_names: [ block1 ]
          device: /dev/xvda
          partition_type: p
          partition_number: 4
          partition_start: ''
          partition_stop: +50G
        - node_names: [ object1 ]
          device: /dev/xvda
          partition_type: e
          partition_number: 3
          partition_start: ''
          partition_stop: ''

    - name: Partition Disk (Logical)
      shell: |
        fdisk {{ item.device }} <<EOF
        n
        l
        {{ item.partition_start }}
        {{ item.partition_stop }}
        w
        EOF
        partprobe {{ item.device }} creates={{ item.device }}{{ item.partition_number }}
      when: node_name in item.node_names
      with_items:
        - node_names: [ object1 ]
          device: /dev/xvda
          partition_type: l
          partition_number: 5
          partition_start: ''
          partition_stop: +20G
        - node_names: [ object1 ]
          device: /dev/xvda
          partition_type: l
          partition_number: 6
          partition_start: ''
          partition_stop: +20G
        - node_names: [ object1 ]
          device: /dev/xvda
          partition_type: l
          partition_number: 7
          partition_start: ''
          partition_stop: +20G
        - node_names: [ object1 ]
          device: /dev/xvda
          partition_type: l
          partition_number: 8
          partition_start: ''
          partition_stop: +20G
        - node_names: [ object1 ]
          device: /dev/xvda
          partition_type: l
          partition_number: 9
          partition_start: ''
          partition_stop: +20G
