heat_template_version: 2013-05-23

description: Deploy A Rackspace Private Cloud 10.1 Reference Architecture Environment

resources:
  password:
    type: OS::Heat::RandomString
    properties:
      length: 12
      sequence: lettersdigits

  keypair:
    type: OS::Nova::KeyPair
    properties:
      name:
        str_replace:
          template: "%prefix%-rpc-keypair"
          params:
            "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
      save_private_key: True

  network:
    type: Rackspace::Cloud::Network
    properties:
      cidr: 192.168.2.0/24
      label:
        str_replace:
          template: "%prefix%-rpc-private"
          params:
            "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }

  swift_signal_handle_infra1:
    type: OS::Heat::SwiftSignalHandle

  swift_signal_handle_infra2:
    type: OS::Heat::SwiftSignalHandle

  cloud_config_infra1:
    type: OS::Heat::CloudConfig
    depends_on: [ password, keypair ]
    properties:
      cloud_config:
        output:
          all: '| tee -a /var/log/cloud-init-output.log'
        apt_upgrade: true
        packages:
          - tmux
          - htop
          - multitail
        write_files:
          - path: /opt/cloud-training/password
            content: { get_attr: [ password, value ] }
            permissions: "0600"
          - path: /opt/cloud-training/id_rsa
            content: { get_attr: [ keypair, private_key ] }
            permissions: "0600"
          - path: /opt/cloud-training/id_rsa.pub
            content: { get_attr: [ keypair, public_key ] }
            permissions: "0644"
        runcmd:
          - |
            %swift_signal_notify% --data-binary '{"status": "SUCCESS"}'

  cloud_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        output:
          all: '| tee -a /var/log/cloud-init-output.log'
        apt_upgrade: true
        packages:
          - tmux
          - htop
          - multitail
        runcmd:
          - |
            %swift_signal_notify% --data-binary '{"status": "SUCCESS"}'

  server_infra1:
    type: OS::Nova::Server
    depends_on: [ password, keypair, network, cloud_config_infra1, swift_signal_handle_infra1, server_infra2 ]
    properties:
      name:
        str_replace:
          template: "%prefix%-infra1"
          params:
            "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
      flavor: 4GB Standard Instance
      image: Ubuntu 14.04 LTS (Trusty Tahr) (PV)
      diskConfig: MANUAL
      networks:
        - uuid: 00000000-0000-0000-0000-000000000000
        - uuid: 11111111-1111-1111-1111-111111111111
        - network: { get_resource: network }
      key_name: { get_resource: keypair }
      admin_pass: { get_attr: [ password, value ] }
      config_drive: True
      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_resource: cloud_config_infra1 }
          params:
            "%swift_signal_notify%": { get_attr: [ swift_signal_handle_infra1, curl_cli ] }

  server_infra2:
    type: OS::Nova::Server
    depends_on: [ password, keypair, network, cloud_config, swift_signal_handle_infra2 ]
    properties:
    properties:
      name:
        str_replace:
          template: "%prefix%-infra2"
          params:
            "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
      flavor: 4GB Standard Instance
      image: Ubuntu 14.04 LTS (Trusty Tahr) (PV)
      diskConfig: MANUAL
      networks:
        - uuid: 00000000-0000-0000-0000-000000000000
        - uuid: 11111111-1111-1111-1111-111111111111
        - network: { get_resource: network }
      key_name: { get_resource: keypair }
      admin_pass: { get_attr: [ password, value ] }
      config_drive: True
      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_resource: cloud_config }
          params:
            "%swift_signal_notify%": { get_attr: [ swift_signal_handle_infra2, curl_cli ] }

outputs:
  password:
    description: Password
    value: { get_attr: [ password, value ] }
  public_key:
    description: Public Key
    value: { get_attr: [ keypair, public_key ] }
  private_key:
    description: Private Key
    value: { get_attr: [ keypair, private_key ] }
  cloud_config:
    description: Cloud Config
    value: { get_attr: [ cloud_config, config ] }
  cloud_config_infra1:
    description: Cloud Config Infra1
    value: { get_attr: [ cloud_config_infra1, config ] }
