---
# This playbook installs Rackspace Private Cloud v10.1

- name: Setup
  hosts: all
  tags:
    - none
  tasks:
    - name: Ping Nodes
      ping:

- name: Setup
  hosts: all
  tags:
    - setup
  tasks:
    - name: Add Nodes Hosts File Entries (Long)
      lineinfile: dest=/etc/hosts regexp='^{{ hostvars[item].ansible_eth2.ipv4.address }} {{ hostvars[item].node_name }}' line='{{ hostvars[item].ansible_eth2.ipv4.address }} {{ hostvars[item].node_name }}' insertafter=EOF state=present
      with_items: groups['all']

    - name: Add Nodes Hosts File Entries (Short)
      lineinfile: dest=/etc/hosts regexp='^{{ hostvars[item].ansible_eth2.ipv4.address }} {{ item }}' line='{{ hostvars[item].ansible_eth2.ipv4.address }} {{ item }}' insertafter=EOF state=present
      with_items: groups['all']

    - name: Add Nodes Hosts File Entries (Node)
      lineinfile: dest=/etc/hosts regexp='^{{ hostvars[item].ansible_eth2.ipv4.address }} {{ "n%02d"|format(hostvars[item].node_id) }}' line='{{ hostvars[item].ansible_eth2.ipv4.address }} {{ "n%02d"|format(hostvars[item].node_id) }}' insertafter=EOF state=present
      with_items: groups['all']

    - name: Check Connectivity
      command: fping {{ item }}
      changed_when: False
      with_items: groups['all']

    - name: Create /etc/ansible/facts.d
      file: path=/etc/ansible/facts.d state=directory

    - name: Create Dummy Fact
      ini_file: dest=/etc/ansible/facts.d/dummy.fact section=dummy option=dummy value=dummy

    - name: Gather Facts
      setup:

    - name: Set Environment Variables and Force Color Prompt
      lineinfile: dest=/root/.bashrc regexp='{{ item.regexp }}' line='{{ item.line }}' insertafter=EOF state=present
      with_items:
        - { regexp: '^(#)?force_color_prompt',      line: 'force_color_prompt=yes' }
        - { regexp: '^export MY_HEAT_STACK_PREFIX', line: 'export MY_HEAT_STACK_PREFIX={{ heat_stack_prefix }}' }
        - { regexp: '^export MY_NODE_ID',           line: 'export MY_NODE_ID={{ node_id }}' }
        - { regexp: '^export MY_IP',                line: 'export MY_IP={{ hostvars[inventory_hostname].ansible_eth2.ipv4.address }}' }
        - { regexp: '^export MY_PRIVATE_IP',        line: 'export MY_PRIVATE_IP={{ hostvars[inventory_hostname].ansible_eth2.ipv4.address }}' }
        - { regexp: '^export MY_PUBLIC_IP',         line: 'export MY_PUBLIC_IP={{ hostvars[inventory_hostname].ansible_eth0.ipv4.address }}' }

    - name: Install Packages
      apt: name={{ item }} state=present
      with_items:
        - colordiff
        - fping

    - name: Create Swap File
      command: dd if=/dev/zero of=/mnt/4GB.swap bs=1024 count=4194304 creates=/mnt/4GB.swap

    - name: Format Swap File
      command: mkswap /mnt/4GB.swap
      changed_when: false

    - name: Check Swap File
      command: swapon -s
      register: check_swap_file
      changed_when: false

    - name: Enable Swap File
      command: swapon /mnt/4GB.swap
      when: "'/mnt/4GB.swap' not in check_swap_file.stdout"

    - name: Add Swap To /etc/fstab
      lineinfile: dest=/etc/fstab regexp='/mnt/4GB.swap  none  swap  sw 0  0' line='/mnt/4GB.swap  none  swap  sw 0  0' insertafter=EOF

    - name: Set Swappiness
      sysctl: name=vm.swappiness value=90 state=present

    - name: Create Primary Partitions
      shell: |
        export PARTITION_START=`parted {{ item.device }} print free | awk '/Free Space/ { print $1 }' | tail -n 1 | sed 's/GB//'`
        export PARTITION_END=`awk "BEGIN { print $PARTITION_START + {{ item.size }} }"`
        parted {{ item.device }} mkpart primary ${PARTITION_START}GB ${PARTITION_END}GB
        partprobe {{ item.device }}
      when: inventory_hostname in groups[ item.group ] and ansible_local.partitions is not defined
      with_items:
        - group: infra
          device: /dev/xvda
          size: 130
        - group: logger
          device: /dev/xvda
          size: 30
        - group: compute
          device: /dev/xvda
          size: 15
        - group: block
          device: /dev/xvda
          size: 20
        - group: block
          device: /dev/xvda
          size: 100
        - group: object
          device: /dev/xvda
          size: 15

    - name: Create Extended Partitions (Extended Partition Will Consume All Free Space)
      shell: |
        export PARTITION_START=`parted {{ item.device }} print free | awk '/Free Space/ { print $1 }' | tail -n 1 | sed 's/GB//'`
        export PARTITION_END=`parted {{ item.device }} print free | awk '/Free Space/ { print $2 }' | tail -n 1 | sed 's/GB//'`
        parted {{ item.device }} mkpart extended ${PARTITION_START}GB ${PARTITION_END}GB
        partprobe {{ item.device }}
      when: inventory_hostname in groups[ item.group ] and ansible_local.partitions is not defined
      with_items:
        - group: object
          device: /dev/xvda

    - name: Create Logical Partitions
      shell: |
        export PARTITION_START=`parted {{ item.device }} print free | awk '/Free Space/ { print $1 }' | tail -n 1 | sed 's/GB//'`
        export PARTITION_END=`awk "BEGIN { print $PARTITION_START + {{ item.size }} }"`
        parted {{ item.device }} mkpart logical ${PARTITION_START}GB ${PARTITION_END}GB
        partprobe {{ item.device }}
      when: inventory_hostname in groups[ item.group ] and ansible_local.partitions is not defined
      with_items:
        - group: object
          device: /dev/xvda
          size: 20
        - group: object
          device: /dev/xvda
          size: 20
        - group: object
          device: /dev/xvda
          size: 20
        - group: object
          device: /dev/xvda
          size: 20
        - group: object
          device: /dev/xvda
          size: 20

    - name: Create Partitions Done Fact
      ini_file: dest=/etc/ansible/facts.d/partitions.fact section=state option=created value=true

- name: Install Compute
  hosts: all
  tags:
    - install-compute
  tasks:
    - name: Check Connectivity
      command: fping {{ item }}
      changed_when: False
      with_items: groups['all']

- name: Install Compute
  hosts: infra[0]
  tags:
    - install-compute
  tasks:
    - name: Genereate SSH Keypair
      command: ssh-keygen -f ~/.ssh/id_rsa -t rsa -q -N "" creates=/root/.ssh/id_rsa.pub

    - name: Get SSH Public Key
      command: cat /root/.ssh/id_rsa.pub
      register: public_key
      changed_when: False

- name: Install Compute
  hosts: all
  tags:
    - install-compute
  tasks:
    - name: Distribute SSH Public Key
      authorized_key: user=root key='{{ hostvars.[ groups.infra|first ].public_key.stdout }}' state=present

- name: Install Compute
  hosts: infra[0]
  tags:
    - install-compute
  tasks:
    - name: Test SSH Connectivity
      command: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no {{ item }} hostname
      changed_when: False
      with_items: groups['all']
